name: Demo manual launched action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print step
        run: echo "Hello world !"
      - name: multiple runs with pipe
        run: |
          echo " second echo"
          echo " third echo"
